import requests
import json
from time import sleep

base_url = "https://api.rasionalisasi.com/api/get-major-by-id/"
ids = [
    "akuntansi"	,
"ilmu-hukum"	,
"manajemen"	,
"teknik-mesin"	,
"teknik-sipil"	,
"teknik-informatika"	,
"agribisnis-sosial-ekonomi-pertanian-"	,
"teknik-elektro"	,
"pendidikan-guru-sekolah-dasar"	,
"sistem-informasi-manajemen-informatika-"	,
"peternakan"	,
"administrasi-publik-administrasi-negara-"	,
"pendidikan-bahasa-inggris"	,
"ilmu-komunikasi"	,
"psikologi"	,
"sosiologi"	,
"pendidikan-bahasa-dan-sastra-indonesia"	,
"ekonomi-pembangunan"	,
"biologi"	,
"teknik-industri"	,
"pendidikan-jasmani-kesehatan-dan-rekreasi"	,
"matematika"	,
"kimia"	,
"ekonomi"	,
"pendidikan-seni-drama-tari-dan-musik-sendratasik-"	,
"ilmu-keperawatan"	,
"administrasi-bisnis-administrasi-niaga-"	,
"pendidikan-matematika"	,
"pendidikan-dokter"	,
"kesehatan-masyarakat"	,
"fisika"	,
"sastra-inggris"	,
"arsitektur"	,
"agroteknologi"	,
"teknik-kimia"	,
"farmasi"	,
"pendidikan-biologi"	,
"pendidikan-sejarah"	,
"pendidikan-anak-usia-dini-paud-"	,
"teknologi-industri-pertanian-agroindustri-"	,
"teknik-lingkungan"	,
"ilmu-gizi"	,
"pendidikan-fisika"	,
"pendidikan-kimia"	,
"teknik-otomasi-manufaktur-dan-mekatronika"	,
"ilmu-politik"	,
"teknik-tenaga-listrik"	,
"kehutanan"	,
"teknologi-pangan"	,
"ilmu-kelautan"	,
"desain-komunikasi-visual"	,
"agroekoteknologi"	,
"manajemen-sumber-daya-perairan"	,
"bisnis-digital"	,
"hubungan-internasional"	,
"teknologi-pasca-panen"	,
"ilmu-komputer"	,
"pendidikan-geografi"	,
"pendidikan-bimbingan-konseling"	,
"statistika"	,
"keuangan-dan-perbankan"	,
"pendidikan-pancasila-dan-kewarganegaraan"	,
"ilmu-pemerintahan"	,
"pendidikan-ilmu-pengetahuan-alam"	,
"pendidikan-kepelatihan-olahraga"	,
"budidaya-perairan-akuakultur-"	,
"software-engineering-rekayasa-perangkat-lunak-"	,
"ekonomi-islam-ekonomi-syariah-"	,
"ilmu-perpustakaan"	,
"sistem-dan-teknologi-informasi"	,
"teknik-geologi"	,
"sistem-komputer"	,
"sastra-indonesia"	,
"teknik-pertanian-dan-biosistem"	,
"teknik-pertambangan"	,
"teknik-perkapalan"	,
"teknik-perencanaan-wilayah-dan-kota-planologi-"	,
"sastra-jepang"	,
"administrasi-perkantoran-kesekretariatan-"	,
"budidaya-perikanan"	,
"teknik-perancangan-jalan-dan-jembatan"	,
"ilmu-keolahragaan"	,
"antropologi"	,
"pariwisata"	,
"kedokteran-hewan"	,
"pendidikan-luar-sekolah"	,
"manajemen-perhotelan"	,
"akuntansi-sektor-publik"	,
"pendidikan-dokter-gigi"	,
"kewirausahaan"	,
"tata-busana"	,
"manajemen-pemasaran-marketing-"	,
"tata-boga"	,
"ilmu-tanah-manajemen-sumberdaya-lahan-"	,
"sistem-multimedia"	,
"data-science"	,
"teknik-otomotif"	,
"teknik-perminyakan"	,
"administrasi-fiskal-perpajakan-"	,
"manajemen-bisnis"	,
"teknik-konversi-energi"	,
"teknik-konstruksi-gedung"	,
"usaha-perjalanan-wisata"	,
"ilmu-sejarah"	,
"agronomi-dan-hortikultura"	,
"geofisika"	,
"kurikulum-dan-teknologi-pendidikan"	,
"agrobisnis-perikanan-sosial-ekonomi-perikanan-"	,
"akuntansi-pajak"	,
"pendidikan-luar-biasa"	,
"proteksi-tanaman-ilmu-hama-dan-penyakit-tumbuhan-"	,
"sastra-cina-sastra-mandarin-"	,
"rekam-medis"	,
"geografi"	,
"sastra-jerman"	,
"jurnalistik"	,
"nutrisi-dan-teknologi-pakan-nutrisi-dan-makanan-ternak-"	,
"sastra-perancis"	,
"ilmu-kesejahteraan-sosial"	,
"tata-rias-dan-kecantikan"	,
"teknologi-hasil-perikanan"	,
"administrasi-pendidikan"	,
"ilmu-keluarga-dan-konsumen"	,
"produksi-ternak"	,
"kesehatan-dan-keselamatan-kerja"	,
"penyuluhan-dan-komunikasi-pertanian"	,
"kebidanan"	,
"aktuaria"	,
"bioteknologi"	,
"animasi"	,
"desain-interior"	,
"teknik-alat-berat"	,
"sastra-arab-sastra-asia-barat-"	,
"teknik-geomatika"	,
"teknik-metalurgi"	,
"pemanfaatan-sumberdaya-perikanan"	,
"pendidikan-bahasa-arab"	,
"seni-kriya"	,
"teknik-kelautan"	,
"manajemen-pendidikan"	,
"manajemen-bisnis-pariwisata"	,
"penginderaan-jauh-dan-sistem-informasi-geografi"	,
"pengelolaan-hutan"	,
"destinasi-pariwisata"	,
"seni-rupa-creative-arts-"	,
"konservasi-sumberdaya-hutan-dan-ekowisata"	,
"transportasi-laut"	,
"seni-tari"	,
"fisioterapi"	,
"ekonomi-bisnis"	,
"hubungan-masyarakat"	,
"seni-karawitan"	,
"teknik-energi-terbarukan"	,
"manajemen-logistik"	,
"business-law"	,
"desain-produk"	,
"teknik-material"	,
"seni-rupa-murni"	,
"arkeologi"	,
"teknik-biomedik-teknobiomedik-"	,
"teknik-geodesi"	,
"pendidikan-agama-islam"	,
"teknik-fisika"	,
"teknik-refrigerasi-dan-tata-udara"	,
"teknik-logistik"	,
"computerized-accounting"	,
"penyiaran-broadcasting-"	,
"periklanan-advertising-"	,
"teknik-sumberdaya-air-teknik-pengairan-"	,
"teknologi-hasil-ternak"	,
"arsitektur-lanskap"	,
"rekayasa-kehutanan"	,
"accounting-information-system-sistem-informasi-akuntansi-"	,
"manajemen-bisnis-unggas"	,
"pemasaran-digital"	,
"manajemen-hutan"	,
"administrasi-keuangan-dan-perbankan"	,
"filsafat"	,
"ekonomi-sumberdaya-dan-lingkungan"	,
"teknologi-industri-benih"	,
"bisnis-internasional"	,
"sistem-informasi-bisnis"	,
"biokimia"	,
"silvikultur"	,
"teknologi-hasil-hutan"	,
"pembangunan-sosial-dan-kesejahteraan"	,
"sastra-rusia"	,
"teknologi-bioproses"	,
"rekayasa-infrastruktur-lingkungan"	,
"kesehatan-lingkungan"	,
"metrologi"	,
"matematika-bisnis"	,
"business-creation"	,
"demografi-dan-pencatatan-sipil"	,
"manajemen-industri-katering"	,
"manajemen-aset"	,
"teknologi-pulp-dan-kertas"	,
"sastra-belanda"	,
"aeronautika-dan-astronautika-teknik-penerbangan-"	,
"bisnis-islam"	,
"mikrobiologi-pertanian"	,
"statistika-terapan-dan-komputasi"	,
]

for major_id in ids:
    url = base_url + major_id
    print(f"Downloading: {url}")

    try:
        res = requests.get(url, timeout=10)
        res.raise_for_status()

        data = res.json()
        filename = f"{major_id}.json"

        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"Saved → {filename}")

    except Exception as e:
        print(f"Error for ID {major_id}: {e}")

    sleep(1)  # rate limit biar tidak dianggap spam
